### ISSUE TITLE
Output of execution

### ISSUE THREAD

**Issue by 0225452** [theforeman/foreman_remote_execution#193]
Does anyone know what table in the foreman database the 'output' is stored in after a job has executed?

**Comment by iNecas** [comment]
Dynflow's structures are used for storing the data. Please share with us what use case you have rather than going to the technical solution right away. Also, please use theforeman-dev mailling list for this kind of questions https://groups.google.com/forum/#!forum/foreman-dev, we're not using the issues here (I will just ask the repo administrator to disable the feature here), therefore closing the issue.
